spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 4e667c7b508a6c13d57a
            client-secret:  6a7e23f26e6ffdab543d8b52d5965eadcf51514f
            client-authentication-method: POST
            scope: name,email,avatar_url
          google:
            client-id: 108864623176-d2gbangfekaqbr7l8s9nf8v7h099ummj.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
            client-authentication-method: POST
          # 네이버는 spring security가 기본적을 제공해주지 않기 때문에 github, google과 달리 많은 정보를 적어줘야한다.
          naver:
            client-id: B2NgABw5SY9RQ5_5qYkx
            client-secret: VXcab2rsku
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
            client-authentication-method: POST
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
