spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: my.academy.company
    password: fakepassword
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  profiles:
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myacademy-db
    username: root
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  token:
    secret: faketoken

server:
  servlet:
    encoding:
      force-response: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: method
    display-request-duration: true

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}       # AWS IAM AccessKey
      secretKey: ${AWS_SECRET_ACCESS_KEY}   # AWS IAM SecretKey
    s3:
      bucket: bucket    # 버킷 이름
    region:
      static: ap-northeast-2
    stack:
      auto: false

payment:
  toss:
    testSecretApiKey: fake
    testClientApiKey: fake

