# github repository Actions 페이지에 나타낼 이름
name: CI/CD

# event trigger
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}
          submodules: true
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Execute Gradle build
        run: ./gradlew clean build -x test -Pprofile=dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: build and release to DockerHub
        env:
          NAME: ${{secrets.DOCKER_USER}}
          APP: myacademy
          NGINX: nginx
        run: |
          docker build -t $NAME/$APP -f ./DockerFile .
          docker build -t $NAME/$NGINX -f ./nginx/DockerFile .
          docker push $NAME/$APP:latest
          docker push $NAME/$NGINX:latest
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        env:
          APP: "myacademy"
          NGINX: "nginx"
          COMPOSE: "/home/ubuntu/compose/docker-compose.yml"
        with:
          username: ubuntu
          host: ${{secrets.EC2_HOST}}
          key: ${{secrets.EC2_KEY}}
          envs: APP, NGINX, COMPOSE
          script_stop: true
          script: |
            sudo docker-compose -f $COMPOSE down --rmi all
            sudo docker pull ${{secrets.DOCKER_USER}}/$APP:latest
            sudo docker pull ${{secrets.DOCKER_USER}}/$NGINX:latest
            sudo docker-compose -f $COMPOSE up -d